### ISSUE TITLE
Nova 4 ?

### ISSUE THREAD

**Issue by scramatte** [michielfb/laravel-nova-time-field#13]
Hi,

Can you add support for Nova 4 ?

Regards

**Comment by michielfb** [comment]
Hi @scramatte ,

Yes, I can do that. I'm working on that right now. I expect to release it somewhere this week.

**Comment by scramatte** [comment]
Thank you very much
The other field doesn’t let set options as yours.



De: Michiel ***@***.***>
Responder a: michielfb/laravel-nova-time-field ***@***.***>
Fecha: miércoles, 8 de febrero de 2023, 19:29
Para: michielfb/laravel-nova-time-field ***@***.***>
CC: * * ***@***.***>, Mention ***@***.***>
Asunto: Re: [michielfb/laravel-nova-time-field] Nova 4 ? (Issue #13)


Hi @scramatte<https://github.com/scramatte> ,

Yes, I can do that. I'm working on that right now. I expect to release it somewhere this week.

**Comment by michielfb** [comment]
Hi @scramatte ,

I just released version 2.0.0 of this package which supports Laravel Nova 4. Please note that you should now use PHP's datetime format instead of momentjs.
