### ISSUE TITLE
Not saving Am or Pm

### ISSUE THREAD

**Issue by ltd300** [michielfb/laravel-nova-time-field#5]
How can I save the time AM or PM in the database? Now is only saving like 10:00.

**Comment by michielfb** [comment]
Whether input field shows AM/PM or uses the 24H format depends on the user preferences of the browser/OS. 

Even when a user enters a date in the AM/PM format it will be posted in a 24H format.

**Comment by ltd300** [comment]
I just realized that is saving in 24H format.
Thank you for your fast response!!
