### ISSUE TITLE
defining seconds

### ISSUE THREAD

**Issue by upperhouse** [michielfb/laravel-nova-time-field#6]
Hey there.
Thank you for making this.
Do you know if there is any trick for allowing users to define seconds in the field?
Currently the seconds seem unresponsive.
I have it setup in Nova as this:

`Time::make('Start Time', 'starttime')->format('HH:mm:ss'),`

thank you!

**Comment by michielfb** [comment]
Hi @upperhouse ,

I've just released [v1.2.0](https://github.com/michielfb/laravel-nova-time-field/releases/tag/1.2.0). This adds the option to set the [step attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Using_the_step_attributel).

You can manually set a step with `withSteps()` or a step of 1 with `withSeconds()`

**Comment by upperhouse** [comment]
Looks great, thank you!
