### ISSUE TITLE
Anyway to avoid formatting null values?

### ISSUE THREAD

**Issue by lenvanessen** [michielfb/laravel-nova-time-field#8]
Our time column is a nullable field, and the display method doesn't check if it's a null or not. Can we edit the indexDisplay a little bit so it checks the value before having momentjs parse it?

![Schermafbeelding 2021-04-02 om 16 26 02](https://user-images.githubusercontent.com/23024452/113424257-2220fd00-93d0-11eb-81a9-2a7f831902d2.png)

**Comment by michielfb** [comment]
Thanks for the report and pull request. I'll merge your pull request.

**Comment by michielfb** [comment]
@lenvanessen I've released v 1.2.1 to fix t his issue.
